### ISSUE TITLE
Nicehash compatibility

### ISSUE THREAD

**Issue by kyleboddy** [JerryWm/Stratum-Proxy-XMR#2]
Getting a lot of rejected shares despite checking the "emu nicehash" option. Any idea what the issue is?

**Comment by JerryWm** [comment]
What kind of error sends a pool? (Click on "Rejected" in the shares panel)

**Comment by JerryWm** [comment]
Also support the miners mode of operation nicehash?

**Comment by kyleboddy** [comment]
Yes, I am using xmr-stak combined and have "use_nicehash" set to TRUE. The errors are nonce-specific "does your miner support nicehash?" issues. I mine on nicehash with these miners with no problem w/o proxy.

**Comment by JerryWm** [comment]
So do you shell a nicehash pool?

**Comment by JerryWm** [comment]
You need to use either my miner (but it's only for cpu and the code is closed) or use 1 to 1 proxy (Max workers = 1 Emu nicehash = false)

**Comment by JerryWm** [comment]
https://github.com/JerryWm/Stratum-Proxy-XMR/blob/45a1c10ed092e667cea5bae9eab1c463a239e60f/src/app/StratumProxy.js#L62 There is a mistake. Incorrect parse of nonce nicehash

**Comment by JerryWm** [comment]
Download the source. Now everything should work. And try again this method. 
**You need to use either my miner (but it's only for cpu and the code is closed) or use 1 to 1 proxy (Max workers = 1 Emu nicehash = false)**

Thank you!

**Comment by kyleboddy** [comment]
So other GPU miners won't work in this setup?

xmrstak/claymore/sgminer -> stratum-proxy -> Nicehash

**Comment by JerryWm** [comment]
The miners do not support the proxy server and Nicehash at the same time. Since nicehash itself is a proxy server, it accumulates miners. It is due to its specification https://github.com/nicehash/Specifications/blob/master/NiceHash_CryptoNight_modification_v1.0.txt , which is supported by most miners, and it became possible to create a cumulative proxy.

**Comment by JerryWm** [comment]
But you can proxy 1 to 1. Then it will work on nicehash

**Comment by kyleboddy** [comment]
So for six miners, six instances of the software running? Or six pools of nicehash in one worker with max worker = 1?

StratumProxy only supports failover, not fractional pooling though, right?

If 1 to 1 means one proxy per miner, then there's not much point in doing that.... right?

**Comment by JerryWm** [comment]
In order to specify proxying 1 in 1, you must specify in the pool settings [Max workers = 1 Emu nicehash = false]

**Comment by JerryWm** [comment]
Look. If you dig at the nicehash pool, then 6 miners will have 6 connections to the pool. All of them will be visible on the "Pools" tab.

**StratumProxy only supports failover, not fractional pooling though, right?** 
If you dig on the pool naisheesh then yes. But around a bunch of other pools, and on them you can combine up to 256 miners.

**Comment by JerryWm** [comment]
**If 1 to 1 means one proxy per miner, then there's not much point in doing that.... right?**
It turns out so.
ps. You can use mine cpuminer, it can be combined and with a pool of naisheesh.
