### ISSUE TITLE
Too many shares are rejected by the pool

### ISSUE THREAD

**Issue by netmebtc** [JerryWm/Stratum-Proxy-XMR#7]
I use three xmr-stack-amd ,ones has 3.8Kh/s ,but 2/3 of the shares are rejected about  by the pool,only 1/3 of shares are accpted, please help to solve it.

![image](https://user-images.githubusercontent.com/32667839/34602771-1e893254-f23c-11e7-9a47-ceb4cadb0270.png)
![image](https://user-images.githubusercontent.com/32667839/34602793-3cc8529a-f23c-11e7-8560-af57d18854df.png)
![image](https://user-images.githubusercontent.com/32667839/34602819-50c46dd8-f23c-11e7-9aa7-faa2ebc0f8d8.png)
![image](https://user-images.githubusercontent.com/32667839/34602840-5c259972-f23c-11e7-92cb-27ba36168079.png)

**Comment by netmebtc** [comment]
If I use only one  xmr-stak-amd to connect proxy, it is ok and  no rejected shares.

**Comment by JerryWm** [comment]
You do not use my miner. 
Therefore, you must set the flag in setting pool [Emu nicehash] to true. Also, in the miner's settings, specify ["use_nicehash": true]

**Comment by netmebtc** [comment]
My miner is  6xVega64 GPUs
I use xmr-stak-amd can get  11.5Kh/s.  I know xmr-stak-amd can not support "use_nicehash:true", and the new version xmr-stak can support nicehash , but new version xmr-stak can not get 11.5kh/s with 6xVega64

**Comment by JerryWm** [comment]
This is problem. 
Because the proxy uses the same principle as nicehash.
But you can use a proxy from 1 to 1. For this, specify in the pool settings [Emu nicehash = false; Max workers = 1;]

**Comment by JerryWm** [comment]
As you understand, the meaning of the unifying proxy disappears. Statistics only.

**Comment by netmebtc** [comment]
I have used the following 3 proxy
![image](https://user-images.githubusercontent.com/32667839/34605321-1b73004a-f246-11e7-9293-68325bcc0d23.png)
I thik the xmrg-proxy is best proxy,but it can not support "no nicehash"  miner,So I think if your proxy can support "no nicehash" miner , then your proxy will be the best xmr proxy .

**Comment by JerryWm** [comment]
The proxy supports any miner in the 1 to 1 mode. Pros with the proxy is the ability to quickly switch the pool into panels and statistics.

**Comment by netmebtc** [comment]
I like quckly switch pool ,so I  use 1 to 1 mode now.  I hope your proxy will be able to provide 1 to n mode and be  compatible with any miner in the future version.  👍
