### ISSUE TITLE
Pool disconnected

### ISSUE THREAD

**Issue by netmebtc** [JerryWm/Stratum-Proxy-XMR#8]
Here I want to thank you very much for developing such a good software.
I use your latest version , when I  edit pool settings "add"  or "save", it will lead to the connecting  pool becomes disconnected. I do not know if this is a problem or it was designed like this.

Whether the development can support "save" or "add" pool parameters, the pool will not be disconnected, continue to maintain its original state.

**Comment by JerryWm** [comment]
> Here I want to thank you very much for developing such a good software.
 Thank you!
> I use your latest version , when I edit pool settings "add" or "save", it will lead to the connecting pool becomes disconnected. I do not know if this is a problem or it was designed like this.
Yes, it should be so.
